### ISSUE TITLE
Emap2sec.py error

### ISSUE THREAD

**Issue by kimdn** [kiharalab/Emap2sec#17]
I'm just using tutorial set (e.g. 1733.mrc).

I think that 
`Trimmap generation`
and
`Input dataset file generation`
ran well.

However,

```
filename='../data/input_file.txt'

echo 'data/input_dataset_file' > $filename

src="/msc/tahoma/apps/emap2sec/20220620/Emap2sec/bin/Emap2sec.py"

python $src $filename --prefix tutorial
```

returned 
![Screen Shot 2022-08-16 at 9 49 49 AM](https://user-images.githubusercontent.com/3903446/184934925-20d1d08c-1265-42c1-b029-e3a2a050229d.png)

This is weird since I copied all trained models properly.

![Screen Shot 2022-08-16 at 10 39 44 AM](https://user-images.githubusercontent.com/3903446/184943954-3bfbfac8-d527-4467-9dfe-a4280d88b476.png)

Indeed, when I added
```
from os.path import exists
file_exists = exists('models/emap2sec_models_exp1/emap2sec_L1_exp.ckpt-108000.meta')
print (file_exists)
```
at line #314, 
it returned True.

Can I get some advice?
Thank you.

**Comment by kimdn** [comment]
I fixed this issue by copying checkpoint files from codeocean's emap2sec part.

**Comment by wang3702** [comment]
Glad to hear that! Also please try to use codeocean of Emap2sec and Emap2sec+ and our newer version Emap2sec+: https://github.com/kiharalab/Emap2secPlus.

**Comment by kimdn** [comment]
> https://github.com/kiharalab/Emap2secPlus

Emap2secPlus looks nice. Maybe more accurate one? Unfortunately, I can't login codeocean without academic email address.

**Comment by wang3702** [comment]
If you don't have an academic account, maybe you can easily clone emap2secplus locally to run. But I do think codeocean can make it much easier for you to configure the environment.
